pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from your Git repository
                git 'https://github.com/rajeshkumar1232/DeployP1.git'
            }
        }

        stage('Build') {
            steps {
                // Build the project using Maven
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                // Run unit tests
                sh 'mvn test'
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Archive the build artifacts (e.g., JAR or WAR files)
                archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            // Clean up workspace after the build
            cleanWs()
        }
        success {
            // Notify about successful build
            echo 'Build succeeded!'
        }
        failure {
            // Notify about failed build
            echo 'Build failed.'
        }
    }
}
