spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
         name: JwtAuthenticationFilter    
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    config:
      import-check:
        enabled: false
server:
  port: 8762
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: AHLsXHX1FrC3CFJEucI7zks2z5SY6Xq2mIS+6vVJAtgyLh6uk5sctZv1GK5pz4slYNi+Tmv4uC+XSssPduDHBw==
  expiration: 3600
